services:
  db:
    image: postgres:16
    container_name: football_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: football
    ports:
      - "5432:5432"
    volumes:
      - football_db_data:/var/lib/postgresql/data

volumes:
  football_db_data: